import Navbar from './components/Navbar'
import MyPic from './components/MyPic'
import './globals.css'
export const metadata = {
  title: "Wiz's Blog ",
  description: 'Generated by Wizzy',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <MyPic />
        {children}
        </body>
    </html>
  )
}
